### ISSUE TITLE
HOL Step by Step- Image 

### ISSUE THREAD

**Issue by daneenec** [solliancenet/Building-the-business-migration-case-with-Windows-Server-and-SQL-Server#2]
@crpietschmann Task 1 , after step 4 there is an image that looks very large in proportion to the rest of the text, the size of this needs to be reduced

**Comment by daneenec** [comment]
Before HOL  
1.	Before HOL- Table of Contents for tasks does not align with content below  

HOL 
1.	There are multiple screen shots that need to have the size reduced. The size of the font in the image should align closely with the rest of the text.  
a.	HOL Exercise 1/ task 1 ( 2 screen shots) 
b.	HOL Exercise 1/ task 3
i.	Step 4
ii.	Step 6
c.	Exercise 1 /Task 4
i.	Step 2 
ii.	Step 4  
d.	Exercise 1/Task 5
i.	Step 3
ii.	Step 6
iii.	Step 8
iv.	Step 10  
v.	Step 17     

2.	 I see where Internet Explorer is still being used in the tooling messages, but for Step 9 where we tell users to use IE to open a browser is this still a valid tool to recommend?  
a.	Exercise 1/Task 3/step2 6-9. 
b.	Exercise 1/Task 5/Step 11 
c.	Exercise 3/Task 2/Step 7-8 

3.	 Exercise 3/ Task 3 – Incomplete  

Readme File  
1. Should the Data Migration Assistant be listed under services and related products? 
2. This document should be updated to include a summary on the HOL 
3. A Workshop Summary is needed under  Abstract

**Comment by crpietschmann** [comment]
2. Internet Explorer is being used as it's the only web browser that is part of Windows Server 2012 R2 that is used on the virtual machines in the existing Tailspin Toys on-premises environment. It's not generally recommended that Admins install web browsers on Servers, since they are not end-user focused machines, unless absolutely necessary, and another browser isn't necessary for these steps in the lab.

@daneenec These items should all be addressed now.
